# Generated by Django 5.1.2 on 2024-10-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_ad_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='owner',
        ),
    ]
